apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-deployment
  labels:
    app: msa-kubernetes
  namespace: msa-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-business
  template:
    metadata:
      labels:
        app: msa-business
    spec:
#      nodeSelector:
#        msa-node: "true"
      containers:
      - env:
          - name: spring.profiles.active
            value: prod
        image: changwng/spring-cloud-msa-business-service:latest
        name: business
        ports:
        - containerPort: 8030
        resources: {}
      restartPolicy: Always
